[functions.admin-login]
verify_jwt = false

[functions.admin-delete-event]
verify_jwt = false

[functions.admin-application-files]
verify_jwt = false

[functions.my-profile-photo]
verify_jwt = false

[functions.submit-application]
verify_jwt = false
